import Head from "next/head";
import React from "react";
import Link from "next/link";
import { useSelector } from "react-redux";
import { selectCart } from "@/store/store";
import { CartType, getCartItemsLength } from "@/store/reducer";

export default function Layout({
  title,
  children,
}: {
  title?: String;
  children: JSX.Element;
}) {
  const cart: CartType[] = useSelector(selectCart);
  const cartItemsLength = getCartItemsLength(cart);

  return (
    <>
      <Head>
        <title>{title ? title + "- jam Store" : "jam Store"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col min-h-screen justify-between">
        <header>
          <nav className="flex justify-between h-12 px-4 items-center shadow-md">
            <Link className="text-lg font-bold" href="/">
              Jam Store
            </Link>
            <div className="flex">
              <Link href="/cart" className="p-2">
                Cart{" "}
                {cartItemsLength > 0 ? (
                  <span
                    className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white"
                    style={{ color: "white" }}
                  >
                    {getCartItemsLength(cart)}
                  </span>
                ) : (
                  ""
                )}
              </Link>
              <Link href="/login" className="p-2">
                Login
              </Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto px-4 mt-4">{children}</main>
        <footer className="flex justify-center items-center h-10 shadow-inner">
          Copyright Jamshaid © 2023 Jam Store
        </footer>
      </div>
    </>
  );
}
