import Head from "next/head";
import React from "react";
import Link from "next/link";

export default function Layout({
  title,
  children,
}: {
  title?: String;
  children: JSX.Element;
}) {
  return (
    <>
      <Head>
        <title>{title ? title + "- jam Store" : "jam Store"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col min-h-screen justify-between">
        <header>
          <nav className="flex justify-between h-12 px-4 items-center shadow-md">
            <Link className="text-lg font-bold" href="/">
              Jam Store
            </Link>
            <div className="flex">
              <Link href="/cart" className="p-2">
                Cart
              </Link>
              <Link href="/cart" className="p-2">
                Login
              </Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto px-4 mt-4">{children}</main>
        <footer className="flex justify-center items-center h-10 shadow-inner">
          Copyright Jamshaid © 2023 Jam Store
        </footer>
      </div>
    </>
  );
}
